USE [JENKINS]

CREATE TABLE JOBS(
	ID INT IDENTITY(1, 1) NOT NULL,
	JOB_NAME VARCHAR(100) NOT NULL,
	INSERT_DATE DATETIME,
	LAST_RECEIVED DATETIME,
	CONSTRAINT PK_JOBS PRIMARY KEY (ID, JOB_NAME)
)

CREATE TABLE BUILDS(  
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	JOB_NAME VARCHAR(100),
	BUILD_NUMBER INT,
	RECEIVE_DATE DATETIME,
	PROCESSED INT DEFAULT 0,
	PROCESSED_FAIL INT DEFAULT 0
)

CREATE TABLE BUILDS_JSON(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	JOB_NAME VARCHAR(100),
	BUILD_NUMBER INT,
	BUILD_URL VARCHAR(MAX),
	BUILD_JSON NVARCHAR(MAX),
	BUILD_JSON_ORIGINAL NVARCHAR(MAX),
	RECEIVE_DATE DATETIME,
	PROCESSED INT DEFAULT 0
)

CREATE TABLE STAGES_JSON(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	JOB_NAME VARCHAR(100),
	BUILD_NUMBER INT,
	STAGES_URL VARCHAR(MAX),
	STAGES_JSON NVARCHAR(MAX),
	STAGES_JSON_ORIGINAL NVARCHAR(MAX),
	RECEIVE_DATE DATETIME,
	PROCESSED INT DEFAULT 0
)

CREATE TABLE TESTS_JSON(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	JOB_NAME VARCHAR(100),
	BUILD_NUMBER INT,
	TESTS_URL VARCHAR(MAX),
	TESTS_JSON NVARCHAR(MAX),
	RECEIVE_DATE DATETIME,
	PROCESSED INT DEFAULT 0
)

/* BUILD DETAILS */
CREATE TABLE BUILD_RESULTS(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	JOB_NAME VARCHAR(100),
	BUILD_NUMBER INT,
	DURATION INT,
	DURATION_ESTIMATED INT,
	FULL_DISPLAY_NAME VARCHAR (100),
	PREVIOUS_BUILD INT,
	RESULT VARCHAR(100),
	PROCESSED INT DEFAULT 0,
	DESCRIPTION VARCHAR(MAX)
)

CREATE TABLE BUILD_CAUSES(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	JOB_NAME VARCHAR(100),
	BUILD_NUMBER INT,
	CLASS VARCHAR(100),
	CAUSE_DESCRIPTION VARCHAR(MAX),
	UPSTREAM_JOB VARCHAR(100),
	UPSTREAM_BUILD INT,
	USER_ID VARCHAR(50),
	USER_NAME VARCHAR(100),
	PROCESSED INT DEFAULT 0
)

CREATE TABLE BUILD_VARIABLES(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	JOB_NAME VARCHAR(100),
	BUILD_NUMBER INT,
	CLASS VARCHAR(100),
	VARIABLE_NAME VARCHAR(100),
	VARIABLE_VALUE VARCHAR(100),
	PROCESSED INT DEFAULT 0
)

CREATE TABLE BUILD_TEST_SUMMARY(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	JOB_NAME VARCHAR(100),
	BUILD_NUMBER INT,
	CLASS VARCHAR(100),
	FAIL_COUNT INT,
	SKIP_COUNT INT,
	TOTAL_COUNT INT,
	PROCESSED INT DEFAULT 0
)

/* STAGES DETAILS */
CREATE TABLE STAGE_RESULTS(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	JOB_NAME VARCHAR(100),
	BUILD_NUMBER INT,
	STARTTIMEMILLIS VARCHAR(MAX),
	ENDTIMEMILLIS VARCHAR(MAX),
	DURATIONMILLIS VARCHAR(MAX),
	QUEUEDURATIONMILLIS VARCHAR(MAX),
	PAUSEDURATIONMILLIS VARCHAR(MAX),
	RESULT VARCHAR(100),
	PROCESSED INT DEFAULT 0
)

CREATE TABLE STAGE_DETAILS(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	JOB_NAME VARCHAR(100),
	BUILD_NUMBER INT,
	STAGE_ID INT,
	STAGE_NAME VARCHAR(200),
	STAGE_NODE VARCHAR(200),
	STARTTIMEMILLIS VARCHAR(MAX),
	DURATIONMILLIS VARCHAR(MAX),
	PAUSEDURATIONMILLIS VARCHAR(MAX),
	RESULT VARCHAR(100),
	PROCESSED INT DEFAULT 0
)

/* TESTS DETAILS */
CREATE TABLE TEST_RESULTS(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	JOB_NAME VARCHAR(100),
	BUILD_NUMBER INT,
	TEST_NAME VARCHAR(MAX),
	TEST_REPORT_URL VARCHAR(MAX),
	AGENT VARCHAR(100),
	DURATION VARCHAR(MAX),
	TIMESTAMP VARCHAR(MAX),
	ERRORS INT,
	WARNINGS INT,
	ERROR INT,
	EXIT_CODE INT,
	FAILED_TO_START VARCHAR(50),
	RESULT VARCHAR(100),
	PROCESSED INT DEFAULT 0,
	FULL_VERSION DESCRIPTION(MAX)
)

CREATE TABLE TEST_EXIT_CODE_DESCRIPTION (
	ID INT IDENTITY(1,1),
	EXIT_CODE VARCHAR(200),
	DESCRIPTION VARCHAR(500)
)
INSERT INTO TEST_EXIT_CODE_DESCRIPTION (EXIT_CODE, DESCRIPTION)  VALUES
	('-2', 'Aborted'),
	('0', 'OK'),
	('1', 'Warnings'),
	('2', 'Errors'),
	('3', 'Not Started'),
	('4', 'Timeout'),
	('127', 'TestExecute Installation Problem'),
	('1000', 'TestExecute Two Instances'),
	('1001', 'Not Enough Disk Space'),
	('-1', 'Unable to Find License'),
	('-6', 'Not Identified -6. (Plugin)'),
	('-10', 'Not Identified -10. (Plugin)'),
	('-13', 'The execution time specified in the command line has expired. (Plugin)')