USE [JENKINS]
GO

/****** Object:  StoredProcedure [dbo].[AddBuildExecution]    Script Date: 03/01/2019 18:39:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Vinicius Gabriel Cabral Paulino>
-- Create date: <25 FEB 2019>
-- Description:	<Add Jenkins jobs executions>
-- =============================================
CREATE PROCEDURE [dbo].[AddBuildExecution]
	-- Add the parameters for the stored procedure here
	@JOB_LEVEL VARCHAR(100),
	@JOB_NAME VARCHAR(100), 
	@BUILD_NUMBER INT,
	@BUILD_URL VARCHAR(MAX),
	@BUILD_JSON NVARCHAR(MAX)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	-- CONVERT THE CHAR STRINGS TO ASC II;
	SET @BUILD_JSON = REPLACE(@BUILD_JSON, 'CHAR(34)', '"');
    SET @BUILD_JSON = REPLACE(@BUILD_JSON, 'CHAR(36)', '$');
	SET @BUILD_JSON = REPLACE(@BUILD_JSON, 'CHAR(37)', '%');
    SET @BUILD_JSON = REPLACE(@BUILD_JSON, 'CHAR(39)', '''');

	SET @BUILD_URL = REPLACE(@BUILD_URL, 'CHAR(37)', '%');

	-- INSERT THE JOB INTO THE CONTROL TABLE;
	IF ( (SELECT COUNT(*) FROM JOBS WHERE JOB_NAME = @JOB_NAME) = 0)
	BEGIN
		INSERT INTO JOBS (JOB_NAME, INSERT_DATE) VALUES (@JOB_NAME, GETDATE());
	END
	ELSE
	BEGIN
		UPDATE JOBS SET LAST_RECEIVED = GETDATE() WHERE JOB_NAME = @JOB_NAME;
	END

	-- CHECK IF THE BUILD ALREADY EXIST AS PROCESSED AND REMOVE THE ITEMS;
	DECLARE @PROCESSED_BUILD INT = (SELECT COUNT(*) FROM BUILDS WHERE JOB_NAME = @JOB_NAME AND BUILD_NUMBER = @BUILD_NUMBER AND PROCESSED = 1);
	IF ( @PROCESSED_BUILD > 0 )
	BEGIN
		EXEC DeleteBuildExecution @JOB_NAME, @BUILD_NUMBER;
	END

	-- INSERT THE MASTER BUILD JSON INTO THE CONTROL TABLES;
    IF (@JOB_LEVEL = 'BUILD')
	BEGIN
		INSERT INTO BUILDS (JOB_NAME, BUILD_NUMBER, RECEIVE_DATE, PROCESSED) VALUES (@JOB_NAME, @BUILD_NUMBER, GETDATE(), 0);
		INSERT INTO BUILDS_JSON (JOB_NAME, BUILD_NUMBER, BUILD_URL, BUILD_JSON, RECEIVE_DATE, PROCESSED) VALUES (@JOB_NAME, @BUILD_NUMBER, @BUILD_URL, @BUILD_JSON, GETDATE(), 0);
	END

	-- INSERT THE STAGES JSON INTO THE CONTROL TABLE;
    IF (@JOB_LEVEL = 'STAGES')
    BEGIN
        INSERT INTO STAGES_JSON (JOB_NAME, BUILD_NUMBER, STAGES_URL, STAGES_JSON, RECEIVE_DATE, PROCESSED) VALUES (@JOB_NAME, @BUILD_NUMBER, @BUILD_URL, @BUILD_JSON, GETDATE(), 0);
    END

	-- INSERT THE TESTS JSON INTO THE CONTROL TABLE;
	IF (@JOB_LEVEL = 'TESTS')
	BEGIN
		INSERT INTO TESTS_JSON (JOB_NAME, BUILD_NUMBER, TESTS_URL, TESTS_JSON, RECEIVE_DATE, PROCESSED) VALUES (@JOB_NAME, @BUILD_NUMBER, @BUILD_URL, @BUILD_JSON, GETDATE(), 0);
	END

END

GO
