USE [JENKINS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Vinicius Gabriel Cabral Paulino>
-- Create date: <09 MAR 2019>
-- Description:	<Remove the build from all the tables>
-- =============================================
CREATE PROCEDURE [dbo].[DeleteBuildExecution]
    @JOB_NAME VARCHAR(100),
    @BUILD_NUMBER INT
AS
BEGIN
    -- DELETE THE BUILD FROM THE TEST TABLES;
    DELETE FROM TEST_RESULTS WHERE JOB_NAME = @JOB_NAME AND BUILD_NUMBER = @BUILD_NUMBER;
    DELETE FROM TESTS_JSON WHERE JOB_NAME = @JOB_NAME AND BUILD_NUMBER = @BUILD_NUMBER;
    
    -- DELETE THE BUILD FROM THE STAGE TABLES;
    DELETE FROM STAGE_RESULTS WHERE JOB_NAME = @JOB_NAME AND BUILD_NUMBER = @BUILD_NUMBER;
    DELETE FROM STAGE_DETAILS WHERE JOB_NAME = @JOB_NAME AND BUILD_NUMBER = @BUILD_NUMBER;
    DELETE FROM STAGES_JSON WHERE JOB_NAME = @JOB_NAME AND BUILD_NUMBER = @BUILD_NUMBER;

    -- DELETE THE BUILD FROM THE BUILD TABLES;
    DELETE FROM BUILD_TEST_SUMMARY WHERE JOB_NAME = @JOB_NAME AND BUILD_NUMBER = @BUILD_NUMBER;
    DELETE FROM BUILD_VARIABLES WHERE JOB_NAME = @JOB_NAME AND BUILD_NUMBER = @BUILD_NUMBER;
    DELETE FROM BUILD_CAUSES WHERE JOB_NAME = @JOB_NAME AND BUILD_NUMBER = @BUILD_NUMBER;
    DELETE FROM BUILD_RESULTS WHERE JOB_NAME = @JOB_NAME AND BUILD_NUMBER = @BUILD_NUMBER;
    DELETE FROM BUILDS_JSON WHERE JOB_NAME = @JOB_NAME AND BUILD_NUMBER = @BUILD_NUMBER;
    
    -- DELETE THE BUILD FROM THE MASTER TABLE;
    DELETE FROM BUILDS WHERE JOB_NAME = @JOB_NAME AND BUILD_NUMBER = @BUILD_NUMBER;
END

GO
